name: setup

runs:
  using: "composite"

  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        install_options: --no-daemon

        extra_nix_config: |
          allow-import-from-derivation = false
          experimental-features = nix-command flakes

          substituters = https://crane.cachix.org
          trusted-public-keys = crane.cachix.org-1:8Scfpmn9w+hGdXH/Q9tTLiYAE/2dnJYRJP7kl80GuRk=

          extra-substituters = https://cache.nixos.org https://crane.cachix.org 
          extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

          extra-substituters = https://nix-community.cachix.org
          extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

    - name: Configure Cachix
      uses: cachix/cachix-action@v14
      with:
        name: crane
            
    - name: Configure Cargo cache
      shell: bash
      run: |
        mkdir -p .github/cargo
        echo "CARGO_HOME=$(pwd)/.github/cargo" >> $GITHUB_ENV

    - uses: actions/cache@v4
      id: nix-cache
      with:
        path: |
          ~/.cache/nix
          ~/.config/nix
        key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}

    - uses: actions/cache@v4
      id: cargo-cache
      with:
        path: |
          .github/cargo
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
