[server]
port = 8989
allow_origin = [""]

[appservice]
id = "commune"
sender_localpart = "public"
access_token = "appservice-access-token"
hs_access_token = "homeserver-access-token"

[appservice.rules]
auto_join = true
invite_by_local_user = true
federation_domain_whitelist = ["matrix.org", "dev.commune.sh"]

[matrix]
homeserver = "http://localhost:8008"
server_name = "commune.sh"

[search]
disabled = false

[logging]
directory = "logs"
filename = "commune.log"

[sentry]
enabled = false
dsn = ""

[redis]
url = "127.0.0.1:6379/0"
pool_size = 20
timeout_secs = 5
cache_ttl = 300

[cache.joined_rooms]
enabled = false
ttl = 3600

[cache.requests]
enabled = true
ttl = 3600

[cache.public_rooms]
enabled = true
ttl = 3600

[cache.room_state]
enabled = true
ttl = 3600

[cache.messages]
enabled = true
ttl = 3600
refresh_ttl = 60

[cache.search]
enabled = false
ttl = 360

[spaces]
default = ["art", "books", "music"] # Will be ignored if include_all is true
include_all = false # Don't set to true if you have a large number of public spaces
cache = true
ttl = 3600

[public_rooms]
curated = false
include_rooms = []
