[server]
port = 8989
allow_origin = [""]

[appservice]
id = "commune"
sender_localpart = "public"
access_token = "appservice-access-token"
hs_access_token = "homeserver-access-token"

[appservice.rules]
auto_join = true
invite_by_local_user = true
federation_domain_whitelist = ["matrix.org", "dev.commune.sh"]

[matrix]
homeserver = "http://localhost:8008"
server_name = "commune.sh"

[redis]
url = "127.0.0.1:6379"
pool_size = 20
timeout_secs = 5
cache_ttl = 300

[cache.requests]
enabled = true
ttl = 3600

[cache.public_rooms]
enabled = true
expire_after = 3600

[cache.room_state]
enabled = true
expire_after = 3600

[cache.messages]
enabled = true
expire_after = 3600

[public_rooms]
curated = false
include_rooms = []
